### ISSUE TITLE
通过MANetWork模块请求到的JSON数据如何解析？

### ISSUE THREAD

**Issue by Darker1998** [fengyunjue/MANetWork#3]
例如：我想获取支付宝签名成功后的订单字符串（alipay_sdk），就是始终无法获取，只可以print打印出来，请教一下我，谢谢！！！
![image](https://user-images.githubusercontent.com/47914523/120275471-ef1dbb80-c2e3-11eb-9bec-68ed9d6a81ab.png)

**Comment by fengyunjue** [comment]
result.value的类型为JSON，JSON为SwiftyJSON中的结构体，你可以通过下面的方式取出alipay_sdk，关于SwiftyJSON的详细用法，可以参考https://github.com/SwiftyJSON/SwiftyJSON

```
if let data = result.value {
    let alipay_sdk = data["result"]["data"]["data"].stringValue
    print(alipay_sdk)
}
```
